// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOkwU9uyPIeddJa2k2yvaTeLjdn1dxcM',
    appId: '1:499085502499:web:60c5a77f2648adcda12996',
    messagingSenderId: '499085502499',
    projectId: 'grovia-cf883',
    authDomain: 'grovia-cf883.firebaseapp.com',
    storageBucket: 'grovia-cf883.firebasestorage.app',
    measurementId: 'G-DWHGB20S1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDU2UxZPsWQSII2kaomUP00pFHD3n9V0',
    appId: '1:499085502499:android:b6720478dac1244aa12996',
    messagingSenderId: '499085502499',
    projectId: 'grovia-cf883',
    storageBucket: 'grovia-cf883.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgwkhxwr2u4WcP4Y-xKm3KOY0bFsFnGg',
    appId: '1:499085502499:ios:abbdc3835056feafa12996',
    messagingSenderId: '499085502499',
    projectId: 'grovia-cf883',
    storageBucket: 'grovia-cf883.firebasestorage.app',
    iosBundleId: 'com.example.grovia',
  );
}
